{% set name = "libgpg-error" %}
{% set version = "1.38" %}
{% set sha256 = "d8988275aa69d7149f931c10442e9e34c0242674249e171592b430ff7b3afd02" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gnupg.org/ftp/gcrypt/libgpg-error/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libgpg-error') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - gettext
  run:
    - gettext

test:
  commands:
    - test -f $PREFIX/lib/libgpg-error.so  # [linux]
    - conda inspect linkages {{ name }}
    - conda inspect objects {{ name }}  # [osx]

about:
  home: https://www.gnupg.org/software/libgpg-error/index.html
  license: GPL-2.0
  license_file: COPYING
  license_family: GPL
  summary: a small library that originally defined common error values for all GnuPG components

extra:
  recipe-maintainers:
    - martindurant
    - mariusvniekerk
