{% set name = "libgpg-error" %}
{% set version = "1.42" %}
{% set sha256 = "fc07e70f6c615f8c4f590a8e37a9b8dd2e2ca1e9408f8e60459c67452b925e23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gnupg.org/ftp/gcrypt/libgpg-error/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libgpg-error') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
    - libtool  # [unix]
    - automake  # [unix]
    - xz  # [unix]
    - gnuconfig  # [osx]
  host:
    - gettext
  run:
    - gettext

test:
  commands:
    - test -f $PREFIX/lib/libgpg-error.so  # [linux]

about:
  home: https://www.gnupg.org/software/libgpg-error/index.html
  license: GPL-2.0-only
  license_file: COPYING
  license_family: GPL
  summary: a small library that originally defined common error values for all GnuPG components

extra:
  recipe-maintainers:
    - martindurant
    - mariusvniekerk
