{% set name = "libgpg-error" %}
{% set version = "1.52" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gnupg.org/ftp/gcrypt/libgpg-error/{{ name }}-{{ version }}.tar.bz2
  sha256: a1d3180cbdf07011e15931ed50561415af6b7305fe672d1cfa484a3dc7f49325

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libgpg-error') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make  # [unix]
    - libtool  # [unix]
    - automake  # [unix]
    - xz  # [unix]
    - gnuconfig  # [osx]
    - gettext-tools
  host:
    - libintl-devel  # [osx]

test:
  commands:
    - test -f $PREFIX/lib/libgpg-error${SHLIB_EXT}  # [unix]

about:
  home: https://www.gnupg.org/software/libgpg-error/index.html
  license: LGPL-2.1-only
  license_file: COPYING
  license_family: GPL
  summary: a small library that originally defined common error values for all GnuPG components

extra:
  recipe-maintainers:
    - martindurant
    - mariusvniekerk
    - xhochy
