schema_version: 1

context:
  name: libgpg-error
  version: 1.55

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://gnupg.org/ftp/gcrypt/libgpg-error/${{ name }}-${{ version }}.tar.bz2
  sha256: 95b178148863f07d45df0cea67e880a79b9ef71f5d230baddc0071128516ef78

build:
  number: 0
  skip: win

requirements:
  build:
    - if: unix
      then: gnuconfig
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - if: unix
      then: make
    - if: unix
      then: libtool
    - if: unix
      then: automake
    - if: unix
      then: xz-tools
    - if: osx
      then: gnuconfig
    - gettext-tools
  host:
    - if: osx
      then: libintl-devel
  run_exports:
    - ${{ pin_subpackage('libgpg-error') }}

tests:
  - script:
      - if: unix
        then: test -f $PREFIX/lib/libgpg-error${SHLIB_EXT}

about:
  license: LGPL-2.1-only
  license_file: COPYING
  summary: a small library that originally defined common error values for all GnuPG components
  homepage: https://www.gnupg.org/software/libgpg-error/index.html

extra:
  recipe-maintainers:
    - martindurant
    - mariusvniekerk
    - xhochy
